ktor {
    deployment {
        port = 8081
        host = 0.0.0.0
    }
    application {
        modules = [ com.chama.groupmoneymanager.ApplicationKt.module ]
    }
}

jwt {
    secret = "my-super-secret-for-jwt"
    issuer = "http://0.0.0.0:8081"
    audience = "group-money-manager-users"
    realm = "Access to the Chama App"
}

database {
    driverClassName = "com.mysql.cj.jdbc.Driver"
    jdbcURL = "jdbc:mysql://localhost:3306/gmm_db"
    username = "root"
    password = "" // IMPORTANT: Make sure this is your real MySQL password
    maximumPoolSize = 3
    isAutoCommit = false
    transactionIsolation = "TRANSACTION_REPEATABLE_READ"
}