ktor {
    deployment {
        port = 8081
        host = 0.0.0.0
    }
    application {
        modules = [ com.chama.mfuko.ApplicationKt.module ]
    }
}

jwt {
    secret = "my-super-secret-for-jwt"
    issuer = "http://0.0.0.0:8081"
    audience = "mfuko-users"
    realm = "Access to the Chama App"
}

database {
    driverClassName = "org.h2.Driver"
    jdbcURL = "jdbc:h2:file:./build/mfuko_db;AUTO_SERVER=TRUE"
    username = "sa"
    password = ""
    maximumPoolSize = 3
    isAutoCommit = false
    transactionIsolation = "TRANSACTION_REPEATABLE_READ"
}